// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -destination=mock_client.go -package=rabbitmq -mock_names ClientInterface=MockClient -source=interface.go
//

// Package rabbitmq is a generated GoMock package.
package rabbitmq

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of ClientInterface interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// Consume mocks base method.
func (m *MockClient) Consume(ctx context.Context, queue string, handler DeliveryHandler, opts *ConsumeOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, queue, handler, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockClientMockRecorder) Consume(ctx, queue, handler, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockClient)(nil).Consume), ctx, queue, handler, opts)
}

// HealthCheck mocks base method.
func (m *MockClient) HealthCheck() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck")
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockClientMockRecorder) HealthCheck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockClient)(nil).HealthCheck))
}

// Publish mocks base method.
func (m *MockClient) Publish(ctx context.Context, queue string, body any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, queue, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockClientMockRecorder) Publish(ctx, queue, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockClient)(nil).Publish), ctx, queue, body)
}

// PublishWithOptions mocks base method.
func (m *MockClient) PublishWithOptions(ctx context.Context, queue string, body any, opts *PublishOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishWithOptions", ctx, queue, body, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishWithOptions indicates an expected call of PublishWithOptions.
func (mr *MockClientMockRecorder) PublishWithOptions(ctx, queue, body, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishWithOptions", reflect.TypeOf((*MockClient)(nil).PublishWithOptions), ctx, queue, body, opts)
}

// PublishWithReply mocks base method.
func (m *MockClient) PublishWithReply(ctx context.Context, queue string, payload, result any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishWithReply", ctx, queue, payload, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishWithReply indicates an expected call of PublishWithReply.
func (mr *MockClientMockRecorder) PublishWithReply(ctx, queue, payload, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishWithReply", reflect.TypeOf((*MockClient)(nil).PublishWithReply), ctx, queue, payload, result)
}
// DeleteQueue mocks base method.
func (m *MockClient) DeleteQueue(ctx context.Context, name string, ifUnused, ifEmpty, noWait bool) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQueue", ctx, name, ifUnused, ifEmpty, noWait)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteQueue indicates an expected call of DeleteQueue.
func (mr *MockClientMockRecorder) DeleteQueue(ctx, name, ifUnused, ifEmpty, noWait any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQueue", reflect.TypeOf((*MockClient)(nil).DeleteQueue), ctx, name, ifUnused, ifEmpty, noWait)
}
